server:
  port: 9042
spring:
  application:
    name: commentReadRepo
  data:
      cassandra:
        local-datacenter: datacenter1
        schema-action: CREATE_IF_NOT_EXISTS
        keyspace-name: uts
        contact-points: cass1
        port: 9042
